////
backing up application data

Module included in the following assemblies:

* day_two_guide/environment_backup.adoc
////

[id='backup-application-data_{context}']
= Backing up application data

In many cases, application data can be backed up using the `oc rsync` command,
assuming `rsync` is installed within the container image. The Red Hat *rhel7*
base image does contain `rsync`. Therefore, all images that are based on *rhel7*
contain it as well. See xref:../cli_reference/basic_cli_operations.adoc#cli-operations-rsync[Troubleshooting and Debugging CLI Operations - rsync].

[WARNING]
====
This is a _generic_ backup of application data and does not take into account
application-specific backup procedures, for example, special export/import
procedures for database systems.
====

Other means of backup may exist depending on the type of the persistent volume
(for example, Cinder, NFS, Gluster, or others).

The paths to back up are also _application specific_. You can determine
what path to back up by looking at the `*mountPath*` for volumes in the
`*deploymentconfig*`.

[discrete]
== Procedure

.Example of Backing up a Jenkins Deployment's Application Data

. Get the application data `*mountPath*` from the `*deploymentconfig*`:
+
----
$ oc get dc/jenkins -o jsonpath='{ .spec.template.spec.containers[?(@.name=="jenkins")].volumeMounts[?(@.name=="jenkins-data")].mountPath }'
/var/lib/jenkins
----

. Get the name of the pod that is currently running:
+
----
$ oc get pod --selector=deploymentconfig=jenkins -o jsonpath='{ .metadata.name }'
jenkins-1-37nux
----

. Use the `oc rsync` command to copy application data:
+
----
$ oc rsync jenkins-1-37nux:/var/lib/jenkins /tmp/
----

[NOTE]
====
This type of application data backup can only be performed while an application
pod is currently running.
====
