////
restoring application data

Module included in the following assemblies:

* admin_guide/assembly_restoring-cluster.adoc
////

[id='restoring-application-data_{context}']
= Restoring application data

The process for restoring application data is similar to the
xref:backup-application-data[application backup procedure] using the `oc rsync`
tool. The same restrictions apply and the process of restoring application data
requires a persistent volume.

[discrete]
== Procedure

.Example of Restoring a Jenkins Deployment's Application Data

. Verify the backup:
+
----
$ ls -la /tmp/jenkins-backup/
total 8
drwxrwxr-x.  3 user     user   20 Sep  6 11:14 .
drwxrwxrwt. 17 root     root 4096 Sep  6 11:16 ..
drwxrwsrwx. 12 user     user 4096 Sep  6 11:14 jenkins
----

. Use the `oc rsync` tool to copy the data into the running pod:
+
----
$ oc rsync /tmp/jenkins-backup/jenkins jenkins-1-37nux:/var/lib
----
+
[NOTE]
====
Depending on the application, you may be required to restart the application.
====

. Restart the application with new data (_optional_):
+
----
$ oc delete pod jenkins-1-37nux
----
+
Alternatively, you can scale down the deployment to 0, and then up again:
+
----
$ oc scale --replicas=0 dc/jenkins
$ oc scale --replicas=1 dc/jenkins
----
