////
backing up other information

Module included in the following assemblies:

* day_two_guide/environment_backup.adoc
////

[id='backing-up-other-files_{context}']
= Backing up other installation files

. Because the restore procedure involves a complete
reinstallation, save all the files used in the initial installation. This may
include:
+
- *_~/.config/openshift/installer.cfg.yml_* (from the
xref:../install_config/install/quick_install.adoc#install-config-install-quick-install[Quick Installation]
method)
- Ansible playbooks and inventory files (from the
xref:../install_config/install/advanced_install.adoc#install-config-install-advanced-install[Advanced
Installation] method)
- *_/etc/yum.repos.d/ose.repo_* (from the
xref:../install_config/install/disconnected_install.adoc#install-config-install-disconnected-install[Disconnected
Installation] method)

. Backup the procedures for post-installation steps. Some installations may
involve steps that are not included in the installer. This may include changes
to the services outside of the control of {product-title} or the installation of
extra services like monitoring agents.
Additional configuration that is not supported yet by the advanced installer
might also be affected, for example when using multiple authentication providers.
