////
scaling etcd using Ansible

Module included in the following assemblies:

* admin_guide/assembly_replace-etcd-member.adoc
* admin_guide/assembly_restoring-cluster.adoc
* admin_guide/assembly_replace-master-host.adoc
////

[id='adding-etcd-host-ansible_{context}']
= Adding a new etcd host using Ansible

[discrete]
== Procedure

. Modify the Ansible inventory file and create a new group named `[new_etcd]`
and add the new host. Then, add the `new_etcd` group as a child of the `[OSEv3]`
group:
+
----
[OSEv3:children]
masters
nodes
etcd
<new_etcd>

... [OUTPUT ABBREVIATED] ...

[etcd]
master-0.example.com
master-1.example.com
master-2.example.com

[new_etcd]
etcd0.example.com
----

. Run the etcd `scaleup` playbook from the host that executed the initial
installation and where the Ansible inventory file is:
+
----
$ ansible-playbook  /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-etcd/scaleup.yml
----

. After the previous step above has completed, modify the inventory file to
reflect the current status by moving the new etcd host from the `[new_etcd]`
group to the `[etcd]` group:
+
----
[OSEv3:children]
masters
nodes
etcd
<new_etcd>

... [OUTPUT ABBREVIATED] ...

[etcd]
master-0.example.com
master-1.example.com
master-2.example.com
etcd0.example.com
----

. If you are using Flannel, modify the `flanneld` service configuration, located at
`/etc/sysconfig/flanneld` on every {product-title} host, to include the new etcd
host:
+
----
FLANNEL_ETCD_ENDPOINTS=https://master-0.example.com:2379,https://master-1.example.com:2379,https://master-2.example.com:2379,https://etcd0.example.com:2379
----

. Restart the `flanneld` service:
+
----
# systemctl restart flanneld.service
----
